### ISSUE TITLE
Server returns '500 Error' message when users compute the same battle

### ISSUE THREAD

**Issue by jashangoraya** [pauloevpr/praetorians-gg#27]
Rejected: Error: Request failed with status code 500

Happens when 2 players are uploading same file concurrently.

**Comment by jashangoraya** [comment]
[SEQUENCE272020002331.zip](https://github.com/pauloevpr/praetorians-gg/files/4167939/SEQUENCE272020002331.zip)
file that caused issue

**Comment by pauloevpr** [comment]
This happens due to database concurrency issues as multiple users try to compute the same battle at the same time. One user will always succeeded - the one the comes through first - whereas the remaining users will fail. If the remaining users re-attempt to compute the battle, they will succeed since the server in this case will identify that the battle as already been computed. 

Therefore, the solution is to retry the operation. 

I will add client-side retry mechanism as this seems to be the easiest solution. I will establish a maximum attempt value of 3 which seems reasonable.
